FROM node:16.13.1-alpine

WORKDIR /app
RUN mkdir -p dist && chown node:node dist
COPY package.json yarn.lock ./
RUN yarn --prod --pure-lockfile --network-timeout 3600000
COPY tsconfig.json tsconfig.build.json jest.config.ts ormconfig.ts ./
COPY src ./src
RUN yarn build

USER node

CMD ["yarn", "start:prod"]