services:
  car-rental-postgres-test:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test

  car-rental-api-test:
    build: .
    entrypoint: yarn test
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    depends_on:
      - car-rental-postgres-test
    environment:
      - NODE_ENV=development
      - TYPEORM_USERNAME=test
      - TYPEORM_PASSWORD=test
      - TYPEORM_DATABASE=test
      - TYPEORM_HOST=car-rental-postgres-test
      - TYPEORM_PORT=5432
      - LOG_LEVEL=warn