FROM node:16.13.1-alpine AS builder
WORKDIR /app
RUN mkdir -p dist && chown node:node dist
COPY package.json yarn.lock ./
RUN yarn --frozen-lockfile
COPY tsconfig.json tsconfig.build.json ormconfig.ts ./
COPY src ./src
RUN yarn build

FROM node:16.13.1-alpine AS prod
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn --prod --frozen-lockfile
COPY --from=builder /app/dist ./dist
USER node
CMD ["yarn", "start:prod"]