services:
  car-rental-postgres:
    image: postgres:14.1-alpine
    ports:
      - 127.0.0.1:5433:5432
    env_file:
      - ./env/postgres.env
    volumes:
      - pgdata-14:/var/lib/postgresql/data
    restart: always

  car-rental-api:
    build:
      context: ./
      dockerfile: Dockerfile.production
    ports:
      - 0.0.0.0:3000:3000
    env_file:
      - ./env/app.env
    restart: always
    depends_on:
      - car-rental-postgres

volumes:
  pgdata-14: